# Generated by Django 5.0.1 on 2024-01-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAllYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField()),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'salary_by_year',
            },
        ),
    ]
