# Generated by Django 5.0.1 on 2024-01-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApplication', '0002_salaryvacyear_alter_salaryallyear_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountAllYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'count_by_year_all',
            },
        ),
        migrations.CreateModel(
            name='CountVacYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'count_by_year_vac',
            },
        ),
    ]
