# Generated by Django 5.0.1 on 2024-01-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApplication', '0003_countallyear_countvacyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAllCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'area_all_count',
            },
        ),
        migrations.CreateModel(
            name='AreaAllSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField()),
                ('salary', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
            options={
                'db_table': 'area_all_salary',
            },
        ),
        migrations.CreateModel(
            name='AreaVacCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'area_vac_count',
            },
        ),
        migrations.CreateModel(
            name='AreaVacSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField()),
                ('salary', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
            options={
                'db_table': 'area_vac_salary',
            },
        ),
    ]
